application:
  host: 0.0.0.0
  port: 5000
database:
  host: localhost
  port: 5432
  username: realworld_tide
  password: realworld_tide
  db: realworld_tide
authentication:
  secret: asupersecretsecret
